### ISSUE TITLE
Template-ize a request form.

### ISSUE THREAD

**Issue by DavidEBest** [codefordayton/friendly-requests#10]
We've received a sample letter from the Cox media folks. It can be templated to include all the information that we've requested.

**Comment by DavidEBest** [comment]
[Ohio Public Records Request Form Letter.docx](https://github.com/codefordayton/friendly-requests/files/1346500/Ohio.Public.Records.Request.Form.Letter.docx)

**Comment by LukeKuenneke** [comment]
Is this implemented, should this issue be closed?


I am trying to get Python to place nice under Windows. I regret trying to develop under Windows.

**Comment by mattbanderson** [comment]
Agree this can be closed. The server has a templated document that it populates with values supplied by the client.
